// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbhbdmfonutgdgoubczs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiaGJkbWZvbnV0Z2Rnb3ViY3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NzM4OTksImV4cCI6MjA1MjE0OTg5OX0.Xnsdeve_NDZtHZ0aH4uYCBhRGYBRJ-ZxKdCV3y0Qom8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);