// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjldzcphwuyplsclulbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqbGR6Y3Bod3V5cGxzY2x1bGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NjA3MzAsImV4cCI6MjA1MjQzNjczMH0.2xb84x4j0kM5gNlT2UGzxFClk1MIJD_Robr9O5aVR0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);